window.COMMUNITY_STAGE_REGISTRY = [
  {
    id: "slither-worm",
    title: "영철을 피해라",
    creator: { name: "zero4uu", avatar: null, github: "zero4uu" },
    genre: "Arcade survival",
    clearCondition: "30초 동안 영철에 닿지 않고 생존하기",
    thumbnail: "./slither-worm/thumbnail.png",
    path: "./slither-worm/index.html",
  },
  {
    id: "vanishing-picks",
    title: "Vanishing Picks",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Luck & Speed",
    clearCondition: "사라지기 전에 통과 선택지를 고르세요",
    thumbnail: "./vanishing-picks/thumbnail.png",
    path: "./vanishing-picks/index.html",
  },
  {
    id: "lightning-dodge",
    title: "Lightning Dodge",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "35초 동안 번개 예고선을 보고 모든 낙뢰를 피하기",
    thumbnail: "./lightning-dodge/thumbnail.png",
    path: "./lightning-dodge/index.html",
  },
  {
    id: "jump-hurdle",
    title: "Jump Hurdle",
    creator: { name: "지현정", avatar: null, github: "jyeonjeeong" },
    genre: "Platformer",
    clearCondition: "30초 동안 장애물을 피하고 문에 도달하면 클리어",
    thumbnail: "./jump-hurdle/thumbnail.png",
    path: "./jump-hurdle/index.html",
  },
  {
    id: "galaxy-boss",
    title: "Galaxy Boss",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade shooter",
    clearCondition: "보스 체력을 모두 깎아 격추하기",
    thumbnail: "./galaxy-boss/thumbnail.png",
    path: "./galaxy-boss/index.html",
  },
  {
    id: "poop-rain-60",
    title: "Poop Rain 15",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "15초 동안 하늘에서 떨어지는 똥을 피하기",
    thumbnail: "./poop-rain/thumbnail.png",
    path: "./poop-rain/index.html",
  },
  {
    id: "whack-a-mole",
    title: "두더지 잡기",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Arcade",
    clearCondition: "30초 안에 두더지 20마리 이상 잡으면 클리어",
    thumbnail: "./whack-a-mole/thumbnail.png",
    path: "./whack-a-mole/index.html",
  },
  {
    id: "wrong-way-runner",
    title: "Wrong Way Runner",
    creator: { name: "collin", avatar: null, github: "collin-gits" },
    genre: "3D Runner",
    clearCondition: "20초 동안 역주행으로 생존하면 클리어",
    thumbnail: "./wrong-way-runner/thumbnail.png",
    path: "./wrong-way-runner/index.html",
  },
  {
    id: "secret-riceball",
    title: "몰래 주먹밥",
    creator: { name: "collin", avatar: null, github: "jungcollin" },
    genre: "Timing",
    clearCondition: "선생님한테 안 걸리고 주먹밥을 모두 먹으면 클리어",
    thumbnail: "./secret-riceball/thumbnail.png",
    path: "./secret-riceball/index.html",
  },
  {
    id: "home-run-relay",
    title: "Home Run Relay",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "sports / precision batting",
    clearCondition: "총 5구 안에 홈런 3개를 치면 클리어",
    thumbnail: "./home-run-relay/thumbnail.png",
    path: "./home-run-relay/index.html",
  },
  {
    id: "penalty-kick",
    title: "승부차기",
    creator: { name: "bobby", avatar: null, github: "ogq-bobby" },
    genre: "Sports",
    clearCondition: "7번의 킥 중 4골 이상 성공",
    thumbnail: "./penalty-kick/thumbnail.png",
    path: "./penalty-kick/index.html",
  },
  {
    id: "stack-tower",
    title: "Stack Tower",
    creator: { name: "Claude", avatar: null, github: null },
    genre: "Arcade precision",
    clearCondition: "블록 10개를 성공적으로 쌓으면 클리어",
    thumbnail: "./stack-tower/thumbnail.png",
    path: "./stack-tower/index.html",
  },
  {
    id: "maze-escape",
    title: "미로 탈출",
    creator: { name: "Claude", avatar: null, github: "jungcollin" },
    genre: "Puzzle",
    clearCondition: "30초 안에 미로 출구에 도달하기",
    thumbnail: "./maze-escape/thumbnail.png",
    path: "./maze-escape/index.html",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    creator: { name: "Claude", avatar: null, github: "jungcollin" },
    genre: "Memory",
    clearCondition: "45초 안에 모든 카드 쌍 맞추기",
    thumbnail: "./memory-match/thumbnail.png",
    path: "./memory-match/index.html",
  },
  {
    id: "shape-dodger",
    title: "Shape Dodger",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "Dodger",
    clearCondition: "20초 동안 빨간 도형 피해 생존",
    thumbnail: "./shape-dodger/thumbnail.png",
    path: "./shape-dodger/index.html",
  },
  {
    id: "coin-catcher",
    title: "Coin Catcher",
    creator: { name: "Claude", avatar: null, github: "anthropics" },
    genre: "Arcade",
    clearCondition: "코인 20개 수집",
    thumbnail: "./coin-catcher/thumbnail.png",
    path: "./coin-catcher/index.html",
  },
  {
    id: "color-shooter",
    title: "색깔 슈터",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "Arcade",
    clearCondition: "20개의 맞는 색상 과녁을 맞추기",
    thumbnail: "./color-shooter/thumbnail.png",
    path: "./color-shooter/index.html",
  },
  {
    id: "color-match",
    title: "색깔 맞추기",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "퍼즐/순발력",
    clearCondition: "15초 안에 같은 색상의 타일을 10번 맞추기",
    thumbnail: "./color-match/thumbnail.png",
    path: "./color-match/index.html",
  },
  {
    id: "bubble-pop",
    title: "버블 팝",
    creator: { name: "Claude", avatar: null, github: "anthropics" },
    genre: "Arcade",
    clearCondition: "30초 안에 버블 25개 터뜨리면 클리어",
    thumbnail: "./bubble-pop/thumbnail.png",
    path: "./bubble-pop/index.html",
  },
  {
    id: "fly-bird",
    title: "날아라 새야",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "아케이드",
    clearCondition: "10초 버티기",
    thumbnail: "./fly-bird/thumbnail.png",
    path: "./fly-bird/index.html",
  },
  {
    id: "neon-shield",
    title: "네온 쉴드",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "아케이드 퍼즐",
    clearCondition: "20초 동안 네온 코어 방어하기",
    thumbnail: "./neon-shield/thumbnail.png",
    path: "./neon-shield/index.html",
  },
  {
    id: "memory-dodge",
    title: "기억의 파편",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "기억 / 닷지",
    clearCondition: "20초 동안 안전 구역을 기억하고 생존하기",
    thumbnail: "./memory-dodge/thumbnail.png",
    path: "./memory-dodge/index.html",
  },
  {
    id: "dusk-subway-weather-mixing-collapse",
    title: "Dusk Subway: Weather Mix",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Climate puzzler / 붕괴하는 라인",
    clearCondition: "붕괴선이 닿기 전에 활공체를 3개 관측대에 모두 착륙시키면 클리어",
    thumbnail: "./dusk-subway-weather-mixing-collapse/thumbnail.png",
    path: "./dusk-subway-weather-mixing-collapse/index.html",
  },
  {
    id: "neon-observatory-orbit-herding-combo",
    title: "Neon Observatory: Orbit Shepherd",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Orbital survival / 콤보 임계치",
    clearCondition: "콤보를 유지하며 위성 3기를 목표 링에 순서대로 통과시키면 클리어",
    thumbnail: "./neon-observatory-orbit-herding-combo/thumbnail.png",
    path: "./neon-observatory-orbit-herding-combo/index.html",
  },
  {
    id: "dusk-subway-echo-weaving-inverse",
    title: "Dusk Subway: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 역전 버스트",
    clearCondition: "역전 구간을 모두 견디고 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./dusk-subway-echo-weaving-inverse/thumbnail.png",
    path: "./dusk-subway-echo-weaving-inverse/index.html",
  },
  {
    id: "moon-greenhouse-orbit-herding-collapse",
    title: "Moon Greenhouse: Orbit Shepherd",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Orbital survival / 붕괴하는 라인",
    clearCondition: "붕괴선이 닿기 전에 위성 3기를 목표 링에 순서대로 통과시키면 클리어",
    thumbnail: "./moon-greenhouse-orbit-herding-collapse/thumbnail.png",
    path: "./moon-greenhouse-orbit-herding-collapse/index.html",
  },
  {
    id: "glass-aquarium-debt-auction-tempo",
    title: "Glass Aquarium: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 시간을 0으로 만들지 않으며 마지막 경매를 넘기면 클리어",
    thumbnail: "./glass-aquarium-debt-auction-tempo/thumbnail.png",
    path: "./glass-aquarium-debt-auction-tempo/index.html",
  },
  {
    id: "storm-archive-weather-mixing-tempo",
    title: "Storm Archive: Weather Mix",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Climate puzzler / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 활공체를 3개 관측대에 모두 착륙시키면 클리어",
    thumbnail: "./storm-archive-weather-mixing-tempo/thumbnail.png",
    path: "./storm-archive-weather-mixing-tempo/index.html",
  },
  {
    id: "biomech-theater-tide-anchoring-sync",
    title: "Biomech Theater: Tide Anchor",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Prediction survival / 동기화 문",
    clearCondition: "동기화 문을 모두 맞춘 뒤 조류 6파를 넘기며 발전기를 지키면 클리어",
    thumbnail: "./biomech-theater-tide-anchoring-sync/thumbnail.png",
    path: "./biomech-theater-tide-anchoring-sync/index.html",
  },
  {
    id: "biomech-theater-weather-mixing-heat",
    title: "Biomech Theater: Weather Mix",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Climate puzzler / 과열 관리",
    clearCondition: "과열을 폭주시키지 않고 활공체를 3개 관측대에 모두 착륙시키면 클리어",
    thumbnail: "./biomech-theater-weather-mixing-heat/thumbnail.png",
    path: "./biomech-theater-weather-mixing-heat/index.html",
  },
  {
    id: "crystal-foundry-debt-auction-charge",
    title: "Crystal Foundry: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 제한 충전",
    clearCondition: "충전을 남기며 시간을 0으로 만들지 않고 마지막 경매를 넘기면 클리어",
    thumbnail: "./crystal-foundry-debt-auction-charge/thumbnail.png",
    path: "./crystal-foundry-debt-auction-charge/index.html",
  },
  {
    id: "dream-motel-debt-auction-heat",
    title: "Dream Motel: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 과열 관리",
    clearCondition: "과열을 폭주시키지 않고 시간을 0으로 만들지 않고 마지막 경매를 넘기면 클리어",
    thumbnail: "./dream-motel-debt-auction-heat/thumbnail.png",
    path: "./dream-motel-debt-auction-heat/index.html",
  },
  {
    id: "dream-motel-gravity-folding-inverse",
    title: "Dream Motel: Gravity Fold",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity courier / 역전 버스트",
    clearCondition: "역전 구간을 모두 견디고 코어를 균열 없이 목적 슬롯까지 옮기면 클리어",
    thumbnail: "./dream-motel-gravity-folding-inverse/thumbnail.png",
    path: "./dream-motel-gravity-folding-inverse/index.html",
  },
  {
    id: "dream-motel-magnet-braiding-tempo",
    title: "Dream Motel: Magnet Braid",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Magnetic routing / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 에너지 구슬 5개를 다른 극 문에 모두 인도하면 클리어",
    thumbnail: "./dream-motel-magnet-braiding-tempo/thumbnail.png",
    path: "./dream-motel-magnet-braiding-tempo/index.html",
  },
  {
    id: "dream-motel-shadow-stitch-shrink",
    title: "Dream Motel: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./dream-motel-shadow-stitch-shrink/thumbnail.png",
    path: "./dream-motel-shadow-stitch-shrink/index.html",
  },
  {
    id: "dream-motel-tide-anchoring-cursed",
    title: "Dream Motel: Tide Anchor",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Prediction survival / 저주 픽업",
    clearCondition: "저주 조합을 버티면서 조류 6파를 넘기며 발전기를 지키면 클리어",
    thumbnail: "./dream-motel-tide-anchoring-cursed/thumbnail.png",
    path: "./dream-motel-tide-anchoring-cursed/index.html",
  },
  {
    id: "dusk-subway-debt-auction-combo",
    title: "Dusk Subway: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 콤보 임계치",
    clearCondition: "콤보를 유지하며 시간을 0으로 만들지 않고 마지막 경매를 넘기면 클리어",
    thumbnail: "./dusk-subway-debt-auction-combo/thumbnail.png",
    path: "./dusk-subway-debt-auction-combo/index.html",
  },
  {
    id: "dusk-subway-shadow-stitch-cursed",
    title: "Dusk Subway: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 저주 픽업",
    clearCondition: "저주를 버티며 4개 제단을 모두 점등",
    thumbnail: "./dusk-subway-shadow-stitch-cursed/thumbnail.png",
    path: "./dusk-subway-shadow-stitch-cursed/index.html",
  },
  {
    id: "glass-aquarium-echo-weaving-sync",
    title: "Glass Aquarium: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 동기화 문",
    clearCondition: "동기화 문을 모두 맞춘 뒤 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./glass-aquarium-echo-weaving-sync/thumbnail.png",
    path: "./glass-aquarium-echo-weaving-sync/index.html",
  },
  {
    id: "glass-aquarium-mirror-theft-inverse",
    title: "Glass Aquarium: Mirror Heist",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Pattern theft stealth / 역전 버스트",
    clearCondition: "역전 구간을 모두 견디고 서로 다른 패턴 3개로 금고 문을 열면 클리어",
    thumbnail: "./glass-aquarium-mirror-theft-inverse/thumbnail.png",
    path: "./glass-aquarium-mirror-theft-inverse/index.html",
  },
  {
    id: "glass-aquarium-orbit-herding-witness",
    title: "Glass Aquarium: Orbit Shepherd",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Orbital survival / 목격 게이지",
    clearCondition: "목격 게이지를 낮게 유지한 채 위성 3기를 목표 링에 순서대로 통과시키면 클리어",
    thumbnail: "./glass-aquarium-orbit-herding-witness/thumbnail.png",
    path: "./glass-aquarium-orbit-herding-witness/index.html",
  },
  {
    id: "glass-aquarium-shadow-stitch-collapse",
    title: "Glass Aquarium: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 붕괴하는 라인",
    clearCondition: "붕괴선이 닿기 전에 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./glass-aquarium-shadow-stitch-collapse/thumbnail.png",
    path: "./glass-aquarium-shadow-stitch-collapse/index.html",
  },
  {
    id: "glass-aquarium-tide-anchoring-charge",
    title: "Glass Aquarium: Tide Anchor",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Prediction survival / 제한 충전",
    clearCondition: "충전을 남기고 조류 6파 동안 발전기를 지키기",
    thumbnail: "./glass-aquarium-tide-anchoring-charge/thumbnail.png",
    path: "./glass-aquarium-tide-anchoring-charge/index.html",
  },
  {
    id: "midnight-harbor-echo-weaving-cursed",
    title: "Midnight Harbor: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 저주 픽업",
    clearCondition: "저주 조합을 버티면서 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./midnight-harbor-echo-weaving-cursed/thumbnail.png",
    path: "./midnight-harbor-echo-weaving-cursed/index.html",
  },
  {
    id: "midnight-harbor-pulse-fencing-tempo",
    title: "Midnight Harbor: Pulse Fence",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Reactive shield action / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 20연속 파형을 반사하면 클리어",
    thumbnail: "./midnight-harbor-pulse-fencing-tempo/thumbnail.png",
    path: "./midnight-harbor-pulse-fencing-tempo/index.html",
  },
  {
    id: "moon-greenhouse-echo-weaving-heat",
    title: "Moon Greenhouse: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 과열 관리",
    clearCondition: "과열을 폭주시키지 않고 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./moon-greenhouse-echo-weaving-heat/thumbnail.png",
    path: "./moon-greenhouse-echo-weaving-heat/index.html",
  },
  {
    id: "moon-greenhouse-magnet-braiding-inverse",
    title: "Moon Greenhouse: Magnet Braid",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Magnetic routing / 역전 버스트",
    clearCondition: "역전 구간을 모두 견디고 에너지 구슬 5개를 다른 극 문에 모두 인도하면 클리어",
    thumbnail: "./moon-greenhouse-magnet-braiding-inverse/thumbnail.png",
    path: "./moon-greenhouse-magnet-braiding-inverse/index.html",
  },
  {
    id: "moon-greenhouse-mirror-theft-tempo",
    title: "Moon Greenhouse: Mirror Heist",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Pattern theft stealth / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 서로 다른 패턴 3개로 금고 문을 열면 클리어",
    thumbnail: "./moon-greenhouse-mirror-theft-tempo/thumbnail.png",
    path: "./moon-greenhouse-mirror-theft-tempo/index.html",
  },
  {
    id: "moon-greenhouse-pulse-fencing-witness",
    title: "Moon Greenhouse: Pulse Fence",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Reactive shield action / 목격 게이지",
    clearCondition: "목격 게이지를 낮게 유지한 채 20연속 파형을 반사하면 클리어",
    thumbnail: "./moon-greenhouse-pulse-fencing-witness/thumbnail.png",
    path: "./moon-greenhouse-pulse-fencing-witness/index.html",
  },
  {
    id: "moon-greenhouse-shadow-stitch-charge",
    title: "Moon Greenhouse: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 제한 충전",
    clearCondition: "충전을 남기며 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./moon-greenhouse-shadow-stitch-charge/thumbnail.png",
    path: "./moon-greenhouse-shadow-stitch-charge/index.html",
  },
  {
    id: "moon-greenhouse-tide-anchoring-shrink",
    title: "Moon Greenhouse: Tide Anchor",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Prediction survival / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 조류 6파를 넘기며 발전기를 지키면 클리어",
    thumbnail: "./moon-greenhouse-tide-anchoring-shrink/thumbnail.png",
    path: "./moon-greenhouse-tide-anchoring-shrink/index.html",
  },
  {
    id: "neon-observatory-debt-auction-witness",
    title: "Neon Observatory: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 목격 게이지",
    clearCondition: "목격 게이지를 낮게 유지한 채 마지막 경매를 넘기기",
    thumbnail: "./neon-observatory-debt-auction-witness/thumbnail.png",
    path: "./neon-observatory-debt-auction-witness/index.html",
  },
  {
    id: "moon-greenhouse-gravity-folding-combo",
    title: "Moon Greenhouse: Gravity Fold",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity courier / 콤보 임계치",
    clearCondition: "콤보를 유지하며 코어를 균열 없이 목적 슬롯까지 옮기면 클리어",
    thumbnail: "./moon-greenhouse-gravity-folding-combo/thumbnail.png",
    path: "./moon-greenhouse-gravity-folding-combo/index.html",
  },
  {
    id: "neon-observatory-echo-weaving-collapse",
    title: "Neon Observatory: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 붕괴하는 라인",
    clearCondition: "붕괴선이 닿기 전에 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./neon-observatory-echo-weaving-collapse/thumbnail.png",
    path: "./neon-observatory-echo-weaving-collapse/index.html",
  },
  {
    id: "neon-observatory-magnet-braiding-shrink",
    title: "Neon Observatory: Magnet Braid",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Magnetic routing / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 에너지 구슬 5개를 다른 극 문에 모두 인도하면 클리어",
    thumbnail: "./neon-observatory-magnet-braiding-shrink/thumbnail.png",
    path: "./neon-observatory-magnet-braiding-shrink/index.html",
  },
  {
    id: "paper-temple-echo-weaving-tempo",
    title: "Paper Temple: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./paper-temple-echo-weaving-tempo/thumbnail.png",
    path: "./paper-temple-echo-weaving-tempo/index.html",
  },
  {
    id: "midnight-harbor-shadow-stitch-heat",
    title: "Midnight Harbor: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 과열 관리",
    clearCondition: "과열을 폭주시키지 않고 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./midnight-harbor-shadow-stitch-heat/thumbnail.png",
    path: "./midnight-harbor-shadow-stitch-heat/index.html",
  },
  {
    id: "paper-temple-shadow-stitch-witness",
    title: "Paper Temple: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 목격 게이지",
    clearCondition: "목격 게이지를 낮게 유지한 채 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./paper-temple-shadow-stitch-witness/thumbnail.png",
    path: "./paper-temple-shadow-stitch-witness/index.html",
  },
  {
    id: "neon-observatory-gravity-folding-charge",
    title: "Neon Observatory: Gravity Fold",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity courier / 제한 충전",
    clearCondition: "충전을 남기며 코어를 목적 슬롯까지 배달하기",
    thumbnail: "./neon-observatory-gravity-folding-charge/thumbnail.png",
    path: "./neon-observatory-gravity-folding-charge/index.html",
  },
  {
    id: "dusk-subway-orbit-herding-shrink",
    title: "Dusk Subway: Orbit Shepherd",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Orbital survival / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 위성 3기를 목표 링에 순서대로 통과시키면 클리어",
    thumbnail: "./dusk-subway-orbit-herding-shrink/thumbnail.png",
    path: "./dusk-subway-orbit-herding-shrink/index.html",
  },
  {
    id: "dusk-subway-gravity-folding-tempo",
    title: "Dusk Subway: Gravity Fold",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity courier / 템포 윈도우",
    clearCondition: "템포 창을 놓치지 않고 코어를 균열 없이 슬롯까지 운반",
    thumbnail: "./dusk-subway-gravity-folding-tempo/thumbnail.png",
    path: "./dusk-subway-gravity-folding-tempo/index.html",
  },
  {
    id: "paper-temple-magnet-braiding-heat",
    title: "Paper Temple: Magnet Braid",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Magnetic routing / 과열 관리",
    clearCondition: "과열을 폭주시키지 않고 에너지 구슬 5개를 다른 극 문에 모두 인도하면 클리어",
    thumbnail: "./paper-temple-magnet-braiding-heat/thumbnail.png",
    path: "./paper-temple-magnet-braiding-heat/index.html",
  },
  {
    id: "midnight-harbor-debt-auction-shrink",
    title: "Midnight Harbor: Debt Auction",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Risk market defense / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 시간을 0으로 만들지 않고 마지막 경매를 넘기면 클리어",
    thumbnail: "./midnight-harbor-debt-auction-shrink/thumbnail.png",
    path: "./midnight-harbor-debt-auction-shrink/index.html",
  },
  {
    id: "paper-temple-pulse-fencing-shrink",
    title: "Paper Temple: Pulse Fence",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Reactive shield action / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 20연속 파형을 반사하면 클리어",
    thumbnail: "./paper-temple-pulse-fencing-shrink/thumbnail.png",
    path: "./paper-temple-pulse-fencing-shrink/index.html",
  },
  {
    id: "paper-temple-weather-mixing-charge",
    title: "Paper Temple: Weather Mix",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Climate puzzler / 제한 충전",
    clearCondition: "충전을 남기며 활공체 3개를 관측대에 모두 착륙시키기",
    thumbnail: "./paper-temple-weather-mixing-charge/thumbnail.png",
    path: "./paper-temple-weather-mixing-charge/index.html",
  },
  {
    id: "storm-archive-echo-weaving-witness",
    title: "Storm Archive: Echo Loom",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Echo puzzler / 목격 게이지",
    clearCondition: "목격 게이지를 낮게 유지한 채 모든 코어 문양을 연결하면 클리어",
    thumbnail: "./storm-archive-echo-weaving-witness/thumbnail.png",
    path: "./storm-archive-echo-weaving-witness/index.html",
  },
  {
    id: "storm-archive-gravity-folding-collapse",
    title: "Storm Archive: Gravity Fold",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity courier / 붕괴하는 라인",
    clearCondition: "붕괴선이 닿기 전에 코어를 균열 없이 목적 슬롯까지 옮기면 클리어",
    thumbnail: "./storm-archive-gravity-folding-collapse/thumbnail.png",
    path: "./storm-archive-gravity-folding-collapse/index.html",
  },
  {
    id: "storm-archive-mirror-theft-shrink",
    title: "Storm Archive: Mirror Heist",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Pattern theft stealth / 축소 아레나",
    clearCondition: "축소 구간 끝까지 버티며 서로 다른 패턴 3개로 금고 문을 열면 클리어",
    thumbnail: "./storm-archive-mirror-theft-shrink/thumbnail.png",
    path: "./storm-archive-mirror-theft-shrink/index.html",
  },
  {
    id: "crystal-foundry-shadow-stitch-sync",
    title: "Crystal Foundry: Shadow Stitch",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light-shadow action / 동기화 문",
    clearCondition: "동기화 문을 모두 맞춘 뒤 봉합 다리로 4개 제단을 모두 점등하면 클리어",
    thumbnail: "./crystal-foundry-shadow-stitch-sync/thumbnail.png",
    path: "./crystal-foundry-shadow-stitch-sync/index.html",
  }
];
