window.COMMUNITY_STAGE_REGISTRY = [
  {
    id: "slither-worm",
    title: "영철을 피해라",
    creator: { name: "zero4uu", avatar: null, github: "zero4uu" },
    genre: "Arcade survival",
    clearCondition: "30초 동안 영철에 닿지 않고 생존하기",
    thumbnail: "./slither-worm/thumbnail.png",
    path: "./slither-worm/index.html",
  },
  {
    id: "vanishing-picks",
    title: "Vanishing Picks",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Luck & Speed",
    clearCondition: "사라지기 전에 통과 선택지를 고르세요",
    thumbnail: "./vanishing-picks/thumbnail.png",
    path: "./vanishing-picks/index.html",
  },
  {
    id: "lightning-dodge",
    title: "Lightning Dodge",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "35초 동안 번개 예고선을 보고 모든 낙뢰를 피하기",
    thumbnail: "./lightning-dodge/thumbnail.png",
    path: "./lightning-dodge/index.html",
  },
  {
    id: "jump-hurdle",
    title: "Jump Hurdle",
    creator: { name: "지현정", avatar: null, github: "jyeonjeeong" },
    genre: "Platformer",
    clearCondition: "30초 동안 장애물을 피하고 문에 도달하면 클리어",
    thumbnail: "./jump-hurdle/thumbnail.png",
    path: "./jump-hurdle/index.html",
  },
  {
    id: "galaxy-boss",
    title: "Galaxy Boss",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade shooter",
    clearCondition: "보스 체력을 모두 깎아 격추하기",
    thumbnail: "./galaxy-boss/thumbnail.png",
    path: "./galaxy-boss/index.html",
  },
  {
    id: "poop-rain-60",
    title: "Poop Rain 15",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "15초 동안 하늘에서 떨어지는 똥을 피하기",
    thumbnail: "./poop-rain/thumbnail.png",
    path: "./poop-rain/index.html",
  },
  {
    id: "whack-a-mole",
    title: "두더지 잡기",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Arcade",
    clearCondition: "30초 안에 두더지 20마리 이상 잡으면 클리어",
    thumbnail: "./whack-a-mole/thumbnail.png",
    path: "./whack-a-mole/index.html",
  },
  {
    id: "wrong-way-runner",
    title: "Wrong Way Runner",
    creator: { name: "collin", avatar: null, github: "collin-gits" },
    genre: "3D Runner",
    clearCondition: "20초 동안 역주행으로 생존하면 클리어",
    thumbnail: "./wrong-way-runner/thumbnail.png",
    path: "./wrong-way-runner/index.html",
  },
  {
    id: "secret-riceball",
    title: "몰래 주먹밥",
    creator: { name: "collin", avatar: null, github: "jungcollin" },
    genre: "Timing",
    clearCondition: "선생님한테 안 걸리고 주먹밥을 모두 먹으면 클리어",
    thumbnail: "./secret-riceball/thumbnail.png",
    path: "./secret-riceball/index.html",
  },
  {
    id: "home-run-relay",
    title: "Home Run Relay",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "sports / precision batting",
    clearCondition: "총 5구 안에 홈런 3개를 치면 클리어",
    thumbnail: "./home-run-relay/thumbnail.png",
    path: "./home-run-relay/index.html",
  },
  {
    id: "penalty-kick",
    title: "승부차기",
    creator: { name: "bobby", avatar: null, github: "ogq-bobby" },
    genre: "Sports",
    clearCondition: "7번의 킥 중 4골 이상 성공",
    thumbnail: "./penalty-kick/thumbnail.png",
    path: "./penalty-kick/index.html",
  },
  {
    id: "stack-tower",
    title: "Stack Tower",
    creator: { name: "Claude", avatar: null, github: null },
    genre: "Arcade precision",
    clearCondition: "블록 10개를 성공적으로 쌓으면 클리어",
    thumbnail: "./stack-tower/thumbnail.png",
    path: "./stack-tower/index.html",
  },
  {
    id: "maze-escape",
    title: "미로 탈출",
    creator: { name: "Claude", avatar: null, github: "jungcollin" },
    genre: "Puzzle",
    clearCondition: "30초 안에 미로 출구에 도달하기",
    thumbnail: "./maze-escape/thumbnail.png",
    path: "./maze-escape/index.html",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    creator: { name: "Claude", avatar: null, github: "jungcollin" },
    genre: "Memory",
    clearCondition: "45초 안에 모든 카드 쌍 맞추기",
    thumbnail: "./memory-match/thumbnail.png",
    path: "./memory-match/index.html",
  },
  {
    id: "shape-dodger",
    title: "Shape Dodger",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "Dodger",
    clearCondition: "20초 동안 빨간 도형 피해 생존",
    thumbnail: "./shape-dodger/thumbnail.png",
    path: "./shape-dodger/index.html",
  },
  {
    id: "coin-catcher",
    title: "Coin Catcher",
    creator: { name: "Claude", avatar: null, github: "anthropics" },
    genre: "Arcade",
    clearCondition: "코인 20개 수집",
    thumbnail: "./coin-catcher/thumbnail.png",
    path: "./coin-catcher/index.html",
  },
  {
    id: "color-shooter",
    title: "색깔 슈터",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "Arcade",
    clearCondition: "20개의 맞는 색상 과녁을 맞추기",
    thumbnail: "./color-shooter/thumbnail.png",
    path: "./color-shooter/index.html",
  },
  {
    id: "color-match",
    title: "색깔 맞추기",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "퍼즐/순발력",
    clearCondition: "15초 안에 같은 색상의 타일을 10번 맞추기",
    thumbnail: "./color-match/thumbnail.png",
    path: "./color-match/index.html",
  },
  {
    id: "bubble-pop",
    title: "버블 팝",
    creator: { name: "Claude", avatar: null, github: "anthropics" },
    genre: "Arcade",
    clearCondition: "30초 안에 버블 25개 터뜨리면 클리어",
    thumbnail: "./bubble-pop/thumbnail.png",
    path: "./bubble-pop/index.html",
  },
  {
    id: "fly-bird",
    title: "날아라 새야",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "아케이드",
    clearCondition: "10초 버티기",
    thumbnail: "./fly-bird/thumbnail.png",
    path: "./fly-bird/index.html",
  },
  {
    id: "neon-shield",
    title: "네온 쉴드",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "아케이드 퍼즐",
    clearCondition: "20초 동안 네온 코어 방어하기",
    thumbnail: "./neon-shield/thumbnail.png",
    path: "./neon-shield/index.html",
  },
  {
    id: "memory-dodge",
    title: "기억의 파편",
    creator: { name: "Jules", avatar: null, github: null },
    genre: "기억 / 닷지",
    clearCondition: "20초 동안 안전 구역을 기억하고 생존하기",
    thumbnail: "./memory-dodge/thumbnail.png",
    path: "./memory-dodge/index.html",
  },
  {
    id: "biomech-theater-debt-auction-collapse",
    title: "산호 정원",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Placement defense",
    clearCondition: "오염 파도를 버텨내면 클리어",
    thumbnail: "./biomech-theater-debt-auction-collapse/thumbnail.png",
    path: "./biomech-theater-debt-auction-collapse/index.html",
  },
  {
    id: "crystal-foundry-gravity-folding-cursed",
    title: "유리공방",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity puzzle",
    clearCondition: "유리를 최종 틀에 무사히 도달시키면 성공",
    thumbnail: "./crystal-foundry-gravity-folding-cursed/thumbnail.png",
    path: "./crystal-foundry-gravity-folding-cursed/index.html",
  },
  {
    id: "crystal-foundry-mirror-theft-collapse",
    title: "수정 광부",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Collection runner",
    clearCondition: "출구 도달 전 수정 20개 수집",
    thumbnail: "./crystal-foundry-mirror-theft-collapse/thumbnail.png",
    path: "./crystal-foundry-mirror-theft-collapse/index.html",
  },
  {
    id: "dream-motel-tide-anchoring-cursed",
    title: "꿈 포수",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Tap catcher",
    clearCondition: "좋은 꿈 20개를 붙잡으면 클리어",
    thumbnail: "./dream-motel-tide-anchoring-cursed/thumbnail.png",
    path: "./dream-motel-tide-anchoring-cursed/index.html",
  },
  {
    id: "dusk-subway-echo-weaving-inverse",
    title: "거울 글씨",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Mirror tracing",
    clearCondition: "15개의 거울 글자를 완성하면 클리어",
    thumbnail: "./dusk-subway-echo-weaving-inverse/thumbnail.png",
    path: "./dusk-subway-echo-weaving-inverse/index.html",
  },
  {
    id: "dusk-subway-magnet-braiding-sync",
    title: "열차 교차로",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Signal routing",
    clearCondition: "5라운드 동안 모든 열차를 올바르게 안내하면 클리어",
    thumbnail: "./dusk-subway-magnet-braiding-sync/thumbnail.png",
    path: "./dusk-subway-magnet-braiding-sync/index.html",
  },
  {
    id: "dusk-subway-weather-mixing-collapse",
    title: "가을 낙엽",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Wind guiding puzzler",
    clearCondition: "15장의 낙엽을 모으면 클리어",
    thumbnail: "./dusk-subway-weather-mixing-collapse/thumbnail.png",
    path: "./dusk-subway-weather-mixing-collapse/index.html",
  },
  {
    id: "glass-aquarium-mirror-theft-inverse",
    title: "해파리 항해",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Fluid navigation",
    clearCondition: "플랑크톤 20개 수집",
    thumbnail: "./glass-aquarium-mirror-theft-inverse/thumbnail.png",
    path: "./glass-aquarium-mirror-theft-inverse/index.html",
  },
  {
    id: "glass-aquarium-orbit-herding-witness",
    title: "연못지기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Herding puzzle",
    clearCondition: "15마리를 고리에 통과시키면 성공",
    thumbnail: "./glass-aquarium-orbit-herding-witness/thumbnail.png",
    path: "./glass-aquarium-orbit-herding-witness/index.html",
  },
  {
    id: "glass-aquarium-shadow-stitch-collapse",
    title: "심해 직조",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Deep-sea puzzle",
    clearCondition: "해구가 무너지기 전에 모든 쌍 연결",
    thumbnail: "./glass-aquarium-shadow-stitch-collapse/thumbnail.png",
    path: "./glass-aquarium-shadow-stitch-collapse/index.html",
  },
  {
    id: "midnight-harbor-pulse-fencing-tempo",
    title: "등대지기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Rhythm guidance",
    clearCondition: "20척의 배를 안전하게 안내하면 클리어",
    thumbnail: "./midnight-harbor-pulse-fencing-tempo/thumbnail.png",
    path: "./midnight-harbor-pulse-fencing-tempo/index.html",
  },
  {
    id: "moon-greenhouse-magnet-braiding-inverse",
    title: "반딧불 목동",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Wind guiding",
    clearCondition: "20마리 반딧불을 등불로 안내하면 클리어",
    thumbnail: "./moon-greenhouse-magnet-braiding-inverse/thumbnail.png",
    path: "./moon-greenhouse-magnet-braiding-inverse/index.html",
  },
  {
    id: "neon-observatory-debt-auction-witness",
    title: "별자리 지도사",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Stealth tracing",
    clearCondition: "모든 별자리 패턴을 완성하면 클리어",
    thumbnail: "./neon-observatory-debt-auction-witness/thumbnail.png",
    path: "./neon-observatory-debt-auction-witness/index.html",
  },
  {
    id: "neon-observatory-gravity-folding-charge",
    title: "별잡이",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Gravity puzzle",
    clearCondition: "충전을 남기고 별 12개를 별자리에 배치",
    thumbnail: "./neon-observatory-gravity-folding-charge/thumbnail.png",
    path: "./neon-observatory-gravity-folding-charge/index.html",
  },
  {
    id: "paper-temple-orbit-herding-cursed",
    title: "향 의식",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Meditative herding",
    clearCondition: "15개 풍경을 통과시키면 성공",
    thumbnail: "./paper-temple-orbit-herding-cursed/thumbnail.png",
    path: "./paper-temple-orbit-herding-cursed/index.html",
  },
  {
    id: "paper-temple-pulse-fencing-shrink",
    title: "지필묵",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Meditative action",
    clearCondition: "20개의 영혼을 흡수하면 봉인 완성",
    thumbnail: "./paper-temple-pulse-fencing-shrink/thumbnail.png",
    path: "./paper-temple-pulse-fencing-shrink/index.html",
  },
  {
    id: "paper-temple-shadow-stitch-witness",
    title: "그림자 인형극",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Shadow matching",
    clearCondition: "12개의 그림자 장면을 완성하면 클리어",
    thumbnail: "./paper-temple-shadow-stitch-witness/thumbnail.png",
    path: "./paper-temple-shadow-stitch-witness/index.html",
  },
  {
    id: "paper-temple-tide-anchoring-collapse",
    title: "서예 달인",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Rhythm stamping",
    clearCondition: "20자를 올바르게 찍으면 클리어",
    thumbnail: "./paper-temple-tide-anchoring-collapse/thumbnail.png",
    path: "./paper-temple-tide-anchoring-collapse/index.html",
  },
  {
    id: "storm-archive-echo-weaving-witness",
    title: "폭풍의 사서",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Stealth sorting",
    clearCondition: "폭풍이 끝나기 전에 모든 페이지 정리",
    thumbnail: "./storm-archive-echo-weaving-witness/thumbnail.png",
    path: "./storm-archive-echo-weaving-witness/index.html",
  },
  {
    id: "moon-greenhouse-weather-mixing-cursed",
    title: "달빛 정원사",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Light puzzle",
    clearCondition: "15송이 꽃을 피우면 클리어",
    thumbnail: "./moon-greenhouse-weather-mixing-cursed/thumbnail.png",
    path: "./moon-greenhouse-weather-mixing-cursed/index.html",
  },
  {
    id: "pottery-wheel",
    title: "도자기 빚기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Shaping simulation",
    clearCondition: "목표 형태와 일치하면 클리어",
    thumbnail: "./pottery-wheel/thumbnail.png",
    path: "./pottery-wheel/index.html",
  },
  {
    id: "rhythm-fishing",
    title: "리듬 낚시",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Rhythm action",
    clearCondition: "물고기 5마리 낚으면 클리어",
    thumbnail: "./rhythm-fishing/thumbnail.png",
    path: "./rhythm-fishing/index.html",
  },
  {
    id: "crystal-garden",
    title: "수정 정원",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Growth simulation",
    clearCondition: "결정으로 영역을 채우면 클리어",
    thumbnail: "./crystal-garden/thumbnail.png",
    path: "./crystal-garden/index.html",
  },
  {
    id: "tightrope-walk",
    title: "줄타기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Balance action",
    clearCondition: "줄 끝까지 도달하면 클리어",
    thumbnail: "./tightrope-walk/thumbnail.png",
    path: "./tightrope-walk/index.html",
  },
  {
    id: "bubble-artist",
    title: "비누방울 장인",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Precision timing",
    clearCondition: "방울 10개를 목표 크기로 만들면 클리어",
    thumbnail: "./bubble-artist/thumbnail.png",
    path: "./bubble-artist/index.html",
  },
  {
    id: "sky-kite",
    title: "하늘 연",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Wind navigation",
    clearCondition: "별 12개를 수집하면 클리어",
    thumbnail: "./sky-kite/thumbnail.png",
    path: "./sky-kite/index.html",
  },
  {
    id: "wildlife-snap",
    title: "야생 포착",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Photography timing",
    clearCondition: "사진 5장을 촬영하면 클리어",
    thumbnail: "./wildlife-snap/thumbnail.png",
    path: "./wildlife-snap/index.html",
  },
  {
    id: "beacon-relay",
    title: "봉화 릴레이",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Chain timing",
    clearCondition: "5개 봉화대를 모두 점화하면 클리어",
    thumbnail: "./beacon-relay/thumbnail.png",
    path: "./beacon-relay/index.html",
  },
  {
    id: "balloon-flight",
    title: "풍선 여행",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Swipe action",
    clearCondition: "하늘 끝까지 도달하면 클리어",
    thumbnail: "./balloon-flight/thumbnail.png",
    path: "./balloon-flight/index.html",
  },
  {
    id: "sand-castle",
    title: "모래성 쌓기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Building defense",
    clearCondition: "모래성 5층을 완성하면 클리어",
    thumbnail: "./sand-castle/thumbnail.png",
    path: "./sand-castle/index.html",
  },
  {
    id: "tuning-master",
    title: "조율사",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Precision timing",
    clearCondition: "8개 현을 정확히 조율하면 클리어",
    thumbnail: "./tuning-master/thumbnail.png",
    path: "./tuning-master/index.html",
  },
  {
    id: "pipe-rush",
    title: "파이프 연결",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Spatial puzzle",
    clearCondition: "물이 출구에 도달하면 클리어",
    thumbnail: "./pipe-rush/thumbnail.png",
    path: "./pipe-rush/index.html",
  },
  {
    id: "tidal-shells",
    title: "조개 줍기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Tide collection",
    clearCondition: "조개 15개를 수집하면 클리어",
    thumbnail: "./tidal-shells/thumbnail.png",
    path: "./tidal-shells/index.html",
  },
  {
    id: "plate-spinner",
    title: "접시 돌리기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Multi-target management",
    clearCondition: "30초 동안 접시를 떨어뜨리지 않으면 클리어",
    thumbnail: "./plate-spinner/thumbnail.png",
    path: "./plate-spinner/index.html",
  },
  {
    id: "shadow-dance",
    title: "그림자 춤",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Rhythm stealth",
    clearCondition: "무대 끝까지 도달하면 클리어",
    thumbnail: "./shadow-dance/thumbnail.png",
    path: "./shadow-dance/index.html",
  },
  {
    id: "snowman-builder",
    title: "눈사람 빚기",
    creator: { name: "jungcollin", avatar: null, github: "jungcollin" },
    genre: "Rolling builder",
    clearCondition: "눈사람 3단을 완성하면 클리어",
    thumbnail: "./snowman-builder/thumbnail.png",
    path: "./snowman-builder/index.html",
  }
];
