window.COMMUNITY_STAGE_REGISTRY = [
  {
    id: "slither-worm",
    title: "영철을 피해라",
    creator: { name: "zero4uu", avatar: null, github: "zero4uu" },
    genre: "Arcade survival",
    clearCondition: "30초 동안 영철에 닿지 않고 생존하기",
    path: "./slither-worm/index.html",
  },
  {
    id: "vanishing-picks",
    title: "Vanishing Picks",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Luck & Speed",
    clearCondition: "사라지기 전에 통과 선택지를 고르세요",
    path: "./vanishing-picks/index.html",
  },
  {
    id: "lightning-dodge",
    title: "Lightning Dodge",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "35초 동안 번개 예고선을 보고 모든 낙뢰를 피하기",
    path: "./lightning-dodge/index.html",
  },
  {
    id: "jump-hurdle",
    title: "Jump Hurdle",
    creator: { name: "지현정", avatar: null, github: "jyeonjeeong" },
    genre: "Platformer",
    clearCondition: "30초 동안 장애물을 피하고 문에 도달하면 클리어",
    path: "./jump-hurdle/index.html",
  },
  {
    id: "galaxy-boss",
    title: "Galaxy Boss",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade shooter",
    clearCondition: "보스 체력을 모두 깎아 격추하기",
    path: "./galaxy-boss/index.html",
  },
  {
    id: "quick-plus-3",
    title: "Quick Plus 3",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Math quiz",
    clearCondition: "쉬운 더하기 3문제를 모두 맞히기",
    path: "./quick-plus-3/index.html",
  },
  {
    id: "poop-rain-60",
    title: "Poop Rain 60",
    creator: { name: "JungCollin", avatar: null, github: "jungcollin" },
    genre: "Arcade survival",
    clearCondition: "60초 동안 하늘에서 떨어지는 똥을 피하기",
    path: "./poop-rain/index.html",
  },
  {
    id: "whack-a-mole",
    title: "두더지 잡기",
    creator: { name: "김우진", avatar: null, github: "ogq-bobby" },
    genre: "Arcade",
    clearCondition: "30초 안에 두더지 20마리 이상 잡으면 클리어",
    path: "./whack-a-mole/index.html",
  }
];
